# Generated by Django 3.2 on 2021-05-03 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='animal',
            name='characteristic_set',
            field=models.ManyToManyField(to='pets.Characteristic'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='pets.group'),
        ),
    ]
