# Generated by Django 3.2 on 2021-11-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20210503_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='characteristic_set',
        ),
        migrations.AddField(
            model_name='animal',
            name='characteristic',
            field=models.ManyToManyField(related_name='animals', to='pets.Characteristic'),
        ),
    ]
