# Generated by Django 3.2 on 2021-11-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20211110_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='characteristic',
            new_name='characteristics',
        ),
    ]
