# Generated by Django 3.2 on 2021-11-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_rename_characteristic_animal_characteristics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristic',
            old_name='characteristic',
            new_name='name',
        ),
    ]
